name = input("Enter your name : ")
age = int(input("Enter your age : "))
marks = int(input("Enter your marks : "))
print(type(name))
print(type(age))
print(type(marks))
print("Welcome : ",name)
print("Age : ",age)
print("Marks : ",marks)